# Generated by Django 6.1.1 on 2026-09-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('DEAD', 'Dead')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField()),
                ('idempotency_key', models.CharField(max_length=225, null=True, unique=True)),
                ('locked_by', models.CharField(max_length=100, null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
